### ISSUE TITLE
TypeError: makeWarning.apply is not a function

### ISSUE THREAD

**Issue by caleb15** [sindresorhus/del-cli#19]
```
fatal: [web0]: FAILED! => {"changed": true, "cmd": ["yarn", "clean"], "delta": "0:00:01.954902", "end": "2020-12-18 20:58:27.120354", "msg": "non-zero return code", "rc": 1, "start": "2020-12-18 20:58:25.165452", "stderr": "/srv/app/node_modules/normalize-package-data/lib/normalize.js:30
  fixer.warn = function() { warn(makeWarning.apply(null, arguments)) }
                                             ^
TypeError: makeWarning.apply is not a function
    at Object.fixer.warn (/srv/app/node_modules/normalize-package-data/lib/normalize.js:30:46)
    at Object.fixReadmeField (/srv/app/node_modules/normalize-package-data/lib/fixer.js:234:12)
    at /srv/app/node_modules/normalize-package-data/lib/normalize.js:32:38
    at Array.forEach (<anonymous>)
    at normalize (/srv/app/node_modules/normalize-package-data/lib/normalize.js:31:15)
    at meow (/srv/app/node_modules/del-cli/node_modules/meow/index.js:78:2)
    at Object.<anonymous> (/srv/app/node_modules/del-cli/cli.js:6:13)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
error Command failed with exit code 1.", "stderr_lines": ["/srv/app/node_modules/normalize-package-data/lib/normalize.js:30", "  fixer.warn = function() { warn(makeWarning.apply(null, arguments)) }", "                                             ^", "TypeError: makeWarning.apply is not a function", "    at Object.fixer.warn (/srv/app/node_modules/normalize-package-data/lib/normalize.js:30:46)", "    at Object.fixReadmeField (/srv/app/node_modules/normalize-package-data/lib/fixer.js:234:12)", "    at /srv/app/node_modules/normalize-package-data/lib/normalize.js:32:38", "    at Array.forEach (<anonymous>)", "    at normalize (/srv/app/node_modules/normalize-package-data/lib/normalize.js:31:15)", "    at meow (/srv/app/node_modules/del-cli/node_modules/meow/index.js:78:2)", "    at Object.<anonymous> (/srv/app/node_modules/del-cli/cli.js:6:13)", "    at Module._compile (internal/modules/cjs/loader.js:1063:30)", "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)", "    at Module.load (internal/modules/cjs/loader.js:928:32)", "error Command failed with exit code 1."], "stdout": "yarn run v1.22.5
$ del-cli ff/static/dist
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.", "stdout_lines": ["yarn run v1.22.5", "$ del-cli ff/static/dist", "info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command."]}

```

**Comment by caleb15** [comment]
Not exactly sure why this happened, I think node_modules got corrupted somehow. deleting node_modules and reinstalling fixed it.
