### ISSUE TITLE
"SyntaxError: Unexpected identifier" on v4.0.0

### ISSUE THREAD

**Issue by bradvogel** [sindresorhus/del-cli#27]
Repro steps on macOS 11: (`$` is bash prompt)

```
$ npm -v
7.19.0
$ node -v
v10.19.0
$ npm i del-cli@4.0.0
npm WARN EBADENGINE Unsupported engine { package: 'del-cli@4.0.0',
npm WARN EBADENGINE   required: { node: '>=12.20' },
npm WARN EBADENGINE   current: { node: 'v10.19.0', npm: '7.19.0' } }
npm WARN EBADENGINE Unsupported engine { package: 'meow@10.1.0',
npm WARN EBADENGINE   required: { node: '>=12.17' },
npm WARN EBADENGINE   current: { node: 'v10.19.0', npm: '7.19.0' } }
npm WARN EBADENGINE Unsupported engine { package: 'camelcase-keys@7.0.0',
npm WARN EBADENGINE   required: { node: '>=12' },
npm WARN EBADENGINE   current: { node: 'v10.19.0', npm: '7.19.0' } }
npm WARN EBADENGINE Unsupported engine { package: 'read-pkg-up@8.0.0',
npm WARN EBADENGINE   required: { node: '>=12' },
npm WARN EBADENGINE   current: { node: 'v10.19.0', npm: '7.19.0' } }
npm WARN EBADENGINE Unsupported engine { package: 'redent@4.0.0',
npm WARN EBADENGINE   required: { node: '>=12' },
npm WARN EBADENGINE   current: { node: 'v10.19.0', npm: '7.19.0' } }
npm WARN EBADENGINE Unsupported engine { package: 'trim-newlines@4.0.2',
npm WARN EBADENGINE   required: { node: '>=12' },
npm WARN EBADENGINE   current: { node: 'v10.19.0', npm: '7.19.0' } }
npm WARN EBADENGINE Unsupported engine { package: 'read-pkg@6.0.0',
npm WARN EBADENGINE   required: { node: '>=12' },
npm WARN EBADENGINE   current: { node: 'v10.19.0', npm: '7.19.0' } }
npm WARN EBADENGINE Unsupported engine { package: 'indent-string@5.0.0',
npm WARN EBADENGINE   required: { node: '>=12' },
npm WARN EBADENGINE   current: { node: 'v10.19.0', npm: '7.19.0' } }
npm WARN EBADENGINE Unsupported engine { package: 'strip-indent@4.0.0',
npm WARN EBADENGINE   required: { node: '>=12' },
npm WARN EBADENGINE   current: { node: 'v10.19.0', npm: '7.19.0' } }

added 23 packages, removed 13 packages, changed 27 packages, and audited 108 packages in 2s

30 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
$ npx del mydirectory
/private/tmp/del-test/node_modules/del-cli/cli.js:2
import meow from 'meow';
       ^^^^

SyntaxError: Unexpected identifier
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
```

**Comment by bradvogel** [comment]
Silly me. I wasn't on the correct node version. Using v12.20 worked
